#!/usr/bin/env python3
"""
Script para exportar cookies do Chrome para formato Netscape
que pode ser usado pelo yt-dlp
"""

import os
import sqlite3
import json
import sys
from pathlib import Path

def get_chrome_cookies_path():
    """Encontrar o caminho para os cookies do Chrome"""
    possible_paths = [
        os.path.expanduser('~/.config/google-chrome/Default/Cookies'),
        os.path.expanduser('~/.config/google-chrome/Default/Network/Cookies'),
        os.path.expanduser('~/Library/Application Support/Google/Chrome/Default/Cookies'),
        os.path.expanduser('~/AppData/Local/Google/Chrome/User Data/Default/Cookies'),
    ]
    
    for path in possible_paths:
        if os.path.exists(path):
            return path
    
    return None

def export_cookies_to_netscape(cookies_path, output_path):
    """Exportar cookies do Chrome para formato Netscape"""
    try:
        # Conectar ao banco de cookies do Chrome
        conn = sqlite3.connect(cookies_path)
        cursor = conn.cursor()
        
        # Query para buscar cookies
        cursor.execute("""
            SELECT host_key, name, value, path, expires_utc, is_secure
            FROM cookies
            WHERE host_key LIKE '%youtube.com%'
        """)
        
        cookies = cursor.fetchall()
        
        # Escrever no formato Netscape
        with open(output_path, 'w') as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# https://curl.se/rfc/cookie_spec.html\n")
            f.write("# This file was generated by export_cookies.py\n\n")
            
            for cookie in cookies:
                host_key, name, value, path, expires_utc, is_secure = cookie
                
                # Converter timestamp do Chrome para timestamp Unix
                # Chrome usa microssegundos desde 1601-01-01
                if expires_utc > 0:
                    # Converter para segundos desde 1970-01-01
                    expires_unix = (expires_utc / 1000000) - 11644473600
                else:
                    expires_unix = 0
                
                # Formato Netscape: domain, domain_specified, path, secure, expires, name, value
                secure_flag = "TRUE" if is_secure else "FALSE"
                domain_specified = "TRUE" if host_key.startswith('.') else "FALSE"
                
                f.write(f"{host_key}\t{domain_specified}\t{path}\t{secure_flag}\t{int(expires_unix)}\t{name}\t{value}\n")
        
        conn.close()
        print(f"Cookies exportados para: {output_path}")
        return True
        
    except Exception as e:
        print(f"Erro ao exportar cookies: {e}")
        return False

def main():
    cookies_path = get_chrome_cookies_path()
    
    if not cookies_path:
        print("Não foi possível encontrar o arquivo de cookies do Chrome")
        print("Caminhos verificados:")
        for path in [
            '~/.config/google-chrome/Default/Cookies',
            '~/Library/Application Support/Google/Chrome/Default/Cookies',
            '~/AppData/Local/Google/Chrome/User Data/Default/Cookies'
        ]:
            print(f"  {os.path.expanduser(path)}")
        return False
    
    output_path = "youtube_cookies.txt"
    
    if export_cookies_to_netscape(cookies_path, output_path):
        print(f"Cookies exportados com sucesso para {output_path}")
        print("Agora você pode usar este arquivo com yt-dlp:")
        print(f"yt-dlp --cookies {output_path} URL_DO_VIDEO")
        return True
    
    return False

if __name__ == "__main__":
    main()